// <auto-generated />
using System;
using DemoTodoListAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DemoTodoListAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260523201953_DataSeeding")]
    partial class DataSeeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DemoTodoListAPI.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("019f18a5-c200-7000-8000-000000000001"),
                            Description = "Software Development coursework and assignments",
                            Name = "University",
                            Order = 1
                        },
                        new
                        {
                            Id = new Guid("019f18a5-c200-7000-8000-000000000002"),
                            Description = "Personal chores, maintenance, and finance",
                            Name = "Home",
                            Order = 2
                        },
                        new
                        {
                            Id = new Guid("019f18a5-c200-7000-8000-000000000003"),
                            Description = "Professional tasks, meetings, and project deadlines",
                            Name = "Work",
                            Order = 3
                        });
                });

            modelBuilder.Entity("DemoTodoListAPI.Entities.Subcategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Subcategories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("019f18a5-c200-7000-8000-00000000000a"),
                            CategoryId = new Guid("019f18a5-c200-7000-8000-000000000001"),
                            Description = "C#, ASP.NET Core, and Database assignments",
                            Name = "Backend Development",
                            Order = 1
                        },
                        new
                        {
                            Id = new Guid("019f18a5-c200-7000-8000-00000000000b"),
                            CategoryId = new Guid("019f18a5-c200-7000-8000-000000000001"),
                            Description = "Angular, React, and UI/UX design",
                            Name = "Frontend Development",
                            Order = 2
                        },
                        new
                        {
                            Id = new Guid("019f18a5-c200-7000-8000-00000000000c"),
                            CategoryId = new Guid("019f18a5-c200-7000-8000-000000000001"),
                            Description = "Docker, CI/CD pipelines, and AWS",
                            Name = "DevOps & Cloud",
                            Order = 3
                        },
                        new
                        {
                            Id = new Guid("019f18a5-c200-7000-8000-00000000000d"),
                            CategoryId = new Guid("019f18a5-c200-7000-8000-000000000002"),
                            Description = "Cleaning, grocery shopping, and maintenance",
                            Name = "Household Chores",
                            Order = 1
                        },
                        new
                        {
                            Id = new Guid("019f18a5-c200-7000-8000-00000000000e"),
                            CategoryId = new Guid("019f18a5-c200-7000-8000-000000000002"),
                            Description = "Budgeting, bills, and investments",
                            Name = "Personal Finance",
                            Order = 2
                        },
                        new
                        {
                            Id = new Guid("019f18a5-c200-7000-8000-000000000011"),
                            CategoryId = new Guid("019f18a5-c200-7000-8000-000000000002"),
                            Description = "Exercise routines, doctor appointments, and meal prepping",
                            Name = "Health & Wellness",
                            Order = 3
                        },
                        new
                        {
                            Id = new Guid("019f18a5-c200-7000-8000-00000000000f"),
                            CategoryId = new Guid("019f18a5-c200-7000-8000-000000000003"),
                            Description = "Sprint tasks and feature development",
                            Name = "Core Projects",
                            Order = 1
                        },
                        new
                        {
                            Id = new Guid("019f18a5-c200-7000-8000-000000000010"),
                            CategoryId = new Guid("019f18a5-c200-7000-8000-000000000003"),
                            Description = "Standups, 1-on-1s, and timesheets",
                            Name = "Meetings & Admin",
                            Order = 2
                        },
                        new
                        {
                            Id = new Guid("019f18a5-c200-7000-8000-000000000012"),
                            CategoryId = new Guid("019f18a5-c200-7000-8000-000000000003"),
                            Description = "Certifications, technical reading, and skill building",
                            Name = "Professional Development",
                            Order = 3
                        });
                });

            modelBuilder.Entity("DemoTodoListAPI.Entities.TodoItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Priority")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<DateTime>("Reminder")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<Guid>("SubcategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.HasIndex("SubcategoryId");

                    b.ToTable("Tasks", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("019f18a5-c200-7000-8000-000000000101"),
                            Description = "Set up PostgreSQL and configure initial migrations.",
                            DueDate = new DateTime(2026, 6, 3, 17, 0, 0, 0, DateTimeKind.Utc),
                            Priority = 3,
                            Reminder = new DateTime(2026, 6, 2, 17, 0, 0, 0, DateTimeKind.Utc),
                            Status = 1,
                            SubcategoryId = new Guid("019f18a5-c200-7000-8000-00000000000a"),
                            Title = "Implement EF Core Migrations"
                        },
                        new
                        {
                            Id = new Guid("019f18a5-c200-7000-8000-000000000102"),
                            Description = "Create the spec for Task Management endpoints.",
                            DueDate = new DateTime(2026, 6, 5, 17, 0, 0, 0, DateTimeKind.Utc),
                            Priority = 2,
                            Reminder = new DateTime(2026, 6, 4, 17, 0, 0, 0, DateTimeKind.Utc),
                            Status = 1,
                            SubcategoryId = new Guid("019f18a5-c200-7000-8000-00000000000a"),
                            Title = "Design REST API Endpoints"
                        },
                        new
                        {
                            Id = new Guid("019f18a5-c200-7000-8000-000000000103"),
                            Description = "Secure the API using modern token authentication.",
                            DueDate = new DateTime(2026, 6, 2, 17, 0, 0, 0, DateTimeKind.Utc),
                            Priority = 3,
                            Reminder = new DateTime(2026, 6, 2, 5, 0, 0, 0, DateTimeKind.Utc),
                            Status = 1,
                            SubcategoryId = new Guid("019f18a5-c200-7000-8000-00000000000a"),
                            Title = "Add JWT Authentication"
                        },
                        new
                        {
                            Id = new Guid("019f18a5-c200-7000-8000-000000000104"),
                            Description = "Achieve 80% coverage on data access layer.",
                            DueDate = new DateTime(2026, 6, 8, 17, 0, 0, 0, DateTimeKind.Utc),
                            Priority = 1,
                            Reminder = new DateTime(2026, 6, 7, 17, 0, 0, 0, DateTimeKind.Utc),
                            Status = 1,
                            SubcategoryId = new Guid("019f18a5-c200-7000-8000-00000000000a"),
                            Title = "Write Repository Unit Tests"
                        },
                        new
                        {
                            Id = new Guid("019f18a5-c200-7000-8000-000000000105"),
                            Description = "Build a responsive Kanban board drag-and-drop view.",
                            DueDate = new DateTime(2026, 6, 6, 17, 0, 0, 0, DateTimeKind.Utc),
                            Priority = 3,
                            Reminder = new DateTime(2026, 6, 5, 17, 0, 0, 0, DateTimeKind.Utc),
                            Status = 1,
                            SubcategoryId = new Guid("019f18a5-c200-7000-8000-00000000000b"),
                            Title = "Create Task Board UI Component"
                        },
                        new
                        {
                            Id = new Guid("019f18a5-c200-7000-8000-000000000106"),
                            Description = "Set up SignalR or state store for live task updates.",
                            DueDate = new DateTime(2026, 6, 9, 17, 0, 0, 0, DateTimeKind.Utc),
                            Priority = 2,
                            Reminder = new DateTime(2026, 6, 8, 17, 0, 0, 0, DateTimeKind.Utc),
                            Status = 1,
                            SubcategoryId = new Guid("019f18a5-c200-7000-8000-00000000000b"),
                            Title = "Integrate State Management"
                        },
                        new
                        {
                            Id = new Guid("019f18a5-c200-7000-8000-000000000107"),
                            Description = "Repair the sidebar collapse glitch on screens under 768px.",
                            DueDate = new DateTime(2026, 5, 31, 17, 0, 0, 0, DateTimeKind.Utc),
                            Priority = 1,
                            Reminder = new DateTime(2026, 5, 30, 17, 0, 0, 0, DateTimeKind.Utc),
                            Status = 2,
                            SubcategoryId = new Guid("019f18a5-c200-7000-8000-00000000000b"),
                            Title = "Fix CSS Layout Bugs on Mobile"
                        },
                        new
                        {
                            Id = new Guid("019f18a5-c200-7000-8000-000000000108"),
                            Description = "Ensure contrast and aria-labels pass WCAG compliance.",
                            DueDate = new DateTime(2026, 6, 11, 17, 0, 0, 0, DateTimeKind.Utc),
                            Priority = 2,
                            Reminder = new DateTime(2026, 6, 10, 17, 0, 0, 0, DateTimeKind.Utc),
                            Status = 1,
                            SubcategoryId = new Guid("019f18a5-c200-7000-8000-00000000000b"),
                            Title = "Submit UI Accessibility Audit"
                        },
                        new
                        {
                            Id = new Guid("019f18a5-c200-7000-8000-000000000109"),
                            Description = "Write Dockerfile and compose setup for local testing.",
                            DueDate = new DateTime(2026, 6, 4, 17, 0, 0, 0, DateTimeKind.Utc),
                            Priority = 3,
                            Reminder = new DateTime(2026, 6, 3, 17, 0, 0, 0, DateTimeKind.Utc),
                            Status = 1,
                            SubcategoryId = new Guid("019f18a5-c200-7000-8000-00000000000c"),
                            Title = "Dockerize the Application"
                        },
                        new
                        {
                            Id = new Guid("019f18a5-c200-7000-8000-000000000110"),
                            Description = "Automate building and running tests on pull requests.",
                            DueDate = new DateTime(2026, 6, 7, 17, 0, 0, 0, DateTimeKind.Utc),
                            Priority = 2,
                            Reminder = new DateTime(2026, 6, 6, 17, 0, 0, 0, DateTimeKind.Utc),
                            Status = 1,
                            SubcategoryId = new Guid("019f18a5-c200-7000-8000-00000000000c"),
                            Title = "Configure GitHub Actions CI"
                        },
                        new
                        {
                            Id = new Guid("019f18a5-c200-7000-8000-000000000111"),
                            Description = "Provision ECS cluster using standard infrastructure.",
                            DueDate = new DateTime(2026, 6, 13, 17, 0, 0, 0, DateTimeKind.Utc),
                            Priority = 3,
                            Reminder = new DateTime(2026, 6, 12, 17, 0, 0, 0, DateTimeKind.Utc),
                            Status = 1,
                            SubcategoryId = new Guid("019f18a5-c200-7000-8000-00000000000c"),
                            Title = "Deploy Staging to AWS ECS"
                        },
                        new
                        {
                            Id = new Guid("019f18a5-c200-7000-8000-000000000112"),
                            Description = "Hook up metrics to track API response times.",
                            DueDate = new DateTime(2026, 6, 15, 17, 0, 0, 0, DateTimeKind.Utc),
                            Priority = 1,
                            Reminder = new DateTime(2026, 6, 14, 17, 0, 0, 0, DateTimeKind.Utc),
                            Status = 1,
                            SubcategoryId = new Guid("019f18a5-c200-7000-8000-00000000000c"),
                            Title = "Setup Prometheus Monitoring"
                        },
                        new
                        {
                            Id = new Guid("019f18a5-c200-7000-8000-000000000113"),
                            Description = "Buy meal prep ingredients, fruits, and snacks.",
                            DueDate = new DateTime(2026, 6, 1, 23, 0, 0, 0, DateTimeKind.Utc),
                            Priority = 2,
                            Reminder = new DateTime(2026, 6, 1, 19, 0, 0, 0, DateTimeKind.Utc),
                            Status = 1,
                            SubcategoryId = new Guid("019f18a5-c200-7000-8000-00000000000d"),
                            Title = "Weekly Grocery Shopping"
                        },
                        new
                        {
                            Id = new Guid("019f18a5-c200-7000-8000-000000000114"),
                            Description = "Clean the oven, fridge shelves, and countertops.",
                            DueDate = new DateTime(2026, 6, 3, 17, 0, 0, 0, DateTimeKind.Utc),
                            Priority = 1,
                            Reminder = new DateTime(2026, 6, 2, 17, 0, 0, 0, DateTimeKind.Utc),
                            Status = 1,
                            SubcategoryId = new Guid("019f18a5-c200-7000-8000-00000000000d"),
                            Title = "Deep Clean Kitchen"
                        },
                        new
                        {
                            Id = new Guid("019f18a5-c200-7000-8000-000000000115"),
                            Description = "Replace the driver module or old LED panel.",
                            DueDate = new DateTime(2026, 5, 29, 17, 0, 0, 0, DateTimeKind.Utc),
                            Priority = 2,
                            Reminder = new DateTime(2026, 5, 28, 17, 0, 0, 0, DateTimeKind.Utc),
                            Status = 3,
                            SubcategoryId = new Guid("019f18a5-c200-7000-8000-00000000000d"),
                            Title = "Fix Hallway Light Fixture"
                        },
                        new
                        {
                            Id = new Guid("019f18a5-c200-7000-8000-000000000116"),
                            Description = "Process via online banking portal.",
                            DueDate = new DateTime(2026, 6, 2, 17, 0, 0, 0, DateTimeKind.Utc),
                            Priority = 3,
                            Reminder = new DateTime(2026, 6, 1, 21, 0, 0, 0, DateTimeKind.Utc),
                            Status = 1,
                            SubcategoryId = new Guid("019f18a5-c200-7000-8000-00000000000e"),
                            Title = "Pay Electricity & Internet Bills"
                        },
                        new
                        {
                            Id = new Guid("019f18a5-c200-7000-8000-000000000117"),
                            Description = "Track savings and variance relative to goals.",
                            DueDate = new DateTime(2026, 6, 5, 17, 0, 0, 0, DateTimeKind.Utc),
                            Priority = 1,
                            Reminder = new DateTime(2026, 6, 4, 17, 0, 0, 0, DateTimeKind.Utc),
                            Status = 1,
                            SubcategoryId = new Guid("019f18a5-c200-7000-8000-00000000000e"),
                            Title = "Review Monthly Budget Spreadsheet"
                        },
                        new
                        {
                            Id = new Guid("019f18a5-c200-7000-8000-000000000118"),
                            Description = "Call local dental clinic to schedule routine cleaning.",
                            DueDate = new DateTime(2026, 6, 10, 14, 0, 0, 0, DateTimeKind.Utc),
                            Priority = 2,
                            Reminder = new DateTime(2026, 6, 9, 14, 0, 0, 0, DateTimeKind.Utc),
                            Status = 1,
                            SubcategoryId = new Guid("019f18a5-c200-7000-8000-000000000011"),
                            Title = "Book Annual Dental Checkup"
                        },
                        new
                        {
                            Id = new Guid("019f18a5-c200-7000-8000-000000000119"),
                            Description = "Swap out old library for a modern, decoupled wrapper.",
                            DueDate = new DateTime(2026, 6, 4, 17, 0, 0, 0, DateTimeKind.Utc),
                            Priority = 3,
                            Reminder = new DateTime(2026, 6, 3, 17, 0, 0, 0, DateTimeKind.Utc),
                            Status = 1,
                            SubcategoryId = new Guid("019f18a5-c200-7000-8000-00000000000f"),
                            Title = "Refactor Legacy Email Module"
                        },
                        new
                        {
                            Id = new Guid("019f18a5-c200-7000-8000-000000000120"),
                            Description = "Add runtime flag config for new dashboard module.",
                            DueDate = new DateTime(2026, 6, 6, 17, 0, 0, 0, DateTimeKind.Utc),
                            Priority = 2,
                            Reminder = new DateTime(2026, 6, 5, 17, 0, 0, 0, DateTimeKind.Utc),
                            Status = 1,
                            SubcategoryId = new Guid("019f18a5-c200-7000-8000-00000000000f"),
                            Title = "Implement Feature Flag Toggle"
                        },
                        new
                        {
                            Id = new Guid("019f18a5-c200-7000-8000-000000000121"),
                            Description = "Optimize query indexing on the active transactions table.",
                            DueDate = new DateTime(2026, 5, 30, 17, 0, 0, 0, DateTimeKind.Utc),
                            Priority = 3,
                            Reminder = new DateTime(2026, 5, 29, 17, 0, 0, 0, DateTimeKind.Utc),
                            Status = 2,
                            SubcategoryId = new Guid("019f18a5-c200-7000-8000-00000000000f"),
                            Title = "Resolve SQL Deadlock Issues"
                        },
                        new
                        {
                            Id = new Guid("019f18a5-c200-7000-8000-000000000122"),
                            Description = "Write API integration setup guides for client teams.",
                            DueDate = new DateTime(2026, 6, 10, 17, 0, 0, 0, DateTimeKind.Utc),
                            Priority = 1,
                            Reminder = new DateTime(2026, 6, 9, 17, 0, 0, 0, DateTimeKind.Utc),
                            Status = 1,
                            SubcategoryId = new Guid("019f18a5-c200-7000-8000-00000000000f"),
                            Title = "Update SDK Documentation"
                        },
                        new
                        {
                            Id = new Guid("019f18a5-c200-7000-8000-000000000123"),
                            Description = "Draft diagrams highlighting planned system scalability changes.",
                            DueDate = new DateTime(2026, 6, 5, 17, 0, 0, 0, DateTimeKind.Utc),
                            Priority = 3,
                            Reminder = new DateTime(2026, 6, 3, 17, 0, 0, 0, DateTimeKind.Utc),
                            Status = 1,
                            SubcategoryId = new Guid("019f18a5-c200-7000-8000-000000000010"),
                            Title = "Prepare Q3 Architecture Slides"
                        },
                        new
                        {
                            Id = new Guid("019f18a5-c200-7000-8000-000000000124"),
                            Description = "Log project allocation codes accurately.",
                            DueDate = new DateTime(2026, 6, 7, 17, 0, 0, 0, DateTimeKind.Utc),
                            Priority = 2,
                            Reminder = new DateTime(2026, 6, 6, 17, 0, 0, 0, DateTimeKind.Utc),
                            Status = 1,
                            SubcategoryId = new Guid("019f18a5-c200-7000-8000-000000000010"),
                            Title = "Submit Bi-Weekly Timesheet"
                        },
                        new
                        {
                            Id = new Guid("019f18a5-c200-7000-8000-000000000125"),
                            Description = "Finish the module on event-driven architectures and message queues.",
                            DueDate = new DateTime(2026, 6, 12, 17, 0, 0, 0, DateTimeKind.Utc),
                            Priority = 1,
                            Reminder = new DateTime(2026, 6, 11, 17, 0, 0, 0, DateTimeKind.Utc),
                            Status = 1,
                            SubcategoryId = new Guid("019f18a5-c200-7000-8000-000000000012"),
                            Title = "Complete Azure Developer Certification Chapter"
                        });
                });

            modelBuilder.Entity("DemoTodoListAPI.Entities.TodoItemFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Path")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<Guid>("TodoItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TodoItemId");

                    b.ToTable("Files", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("019f18a5-c200-7000-8000-000000000301"),
                            ContentType = "application/pdf",
                            Name = "refactoring-spec.pdf",
                            Path = "/files/work/refactoring-spec.pdf",
                            TodoItemId = new Guid("019f18a5-c200-7000-8000-000000000119"),
                            UploadedAt = new DateTime(2026, 6, 1, 17, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("DemoTodoListAPI.Entities.TodoItemStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<Guid>("TodoItemId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TodoItemId");

                    b.ToTable("Steps", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("019f18a5-c200-7000-8000-000000000201"),
                            Order = 1,
                            Title = "Add EF Core Nuget Packages",
                            TodoItemId = new Guid("019f18a5-c200-7000-8000-000000000101")
                        },
                        new
                        {
                            Id = new Guid("019f18a5-c200-7000-8000-000000000202"),
                            Order = 2,
                            Title = "Create ApplicationDbContext class",
                            TodoItemId = new Guid("019f18a5-c200-7000-8000-000000000101")
                        },
                        new
                        {
                            Id = new Guid("019f18a5-c200-7000-8000-000000000203"),
                            Order = 3,
                            Title = "Run 'dotnet ef migrations add Initial'",
                            TodoItemId = new Guid("019f18a5-c200-7000-8000-000000000101")
                        });
                });

            modelBuilder.Entity("DemoTodoListAPI.Entities.Subcategory", b =>
                {
                    b.HasOne("DemoTodoListAPI.Entities.Category", "Category")
                        .WithMany("Subcategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("DemoTodoListAPI.Entities.TodoItem", b =>
                {
                    b.HasOne("DemoTodoListAPI.Entities.Subcategory", "Subcategory")
                        .WithMany("TodoItems")
                        .HasForeignKey("SubcategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subcategory");
                });

            modelBuilder.Entity("DemoTodoListAPI.Entities.TodoItemFile", b =>
                {
                    b.HasOne("DemoTodoListAPI.Entities.TodoItem", "TodoItem")
                        .WithMany("TodoItemFiles")
                        .HasForeignKey("TodoItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TodoItem");
                });

            modelBuilder.Entity("DemoTodoListAPI.Entities.TodoItemStep", b =>
                {
                    b.HasOne("DemoTodoListAPI.Entities.TodoItem", "TodoItem")
                        .WithMany("TodoItemSteps")
                        .HasForeignKey("TodoItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TodoItem");
                });

            modelBuilder.Entity("DemoTodoListAPI.Entities.Category", b =>
                {
                    b.Navigation("Subcategories");
                });

            modelBuilder.Entity("DemoTodoListAPI.Entities.Subcategory", b =>
                {
                    b.Navigation("TodoItems");
                });

            modelBuilder.Entity("DemoTodoListAPI.Entities.TodoItem", b =>
                {
                    b.Navigation("TodoItemFiles");

                    b.Navigation("TodoItemSteps");
                });
#pragma warning restore 612, 618
        }
    }
}
